# Generated by Django 4.0.2 on 2022-12-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_systembankaccount_withdrawtransaction_userbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionId',
        ),
    ]
