# Generated by Django 4.0.2 on 2022-12-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_bio'),
        ('payment', '0005_remove_transaction_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittransaction',
            name='systemBankAccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bankaccount'),
        ),
    ]
