# Generated by Django 4.0.2 on 2022-12-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_withdrawtransaction_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='profileView',
        ),
        migrations.DeleteModel(
            name='ProfileViewTransaction',
        ),
    ]
