# Generated by Django 4.0.2 on 2022-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_transaction_profileview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpaymenttransaction',
            name='receiveAmount',
            field=models.IntegerField(default=0),
        ),
    ]
