# Generated by Django 4.0.2 on 2022-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_paymentmethod_remove_paymentmethod_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpayment',
            name='amount',
            field=models.IntegerField(default=50000),
        ),
    ]
