# Generated by Django 4.0.2 on 2022-11-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
