# Generated by Django 4.0.2 on 2022-12-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.address'),
        ),
    ]
