# Generated by Django 4.0.2 on 2022-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_delete_jobvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
