# Generated by Django 4.0.2 on 2023-01-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_createat_job_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Closed', 'Closed'), ('Payed', 'Payed')], default='Pending'),
        ),
    ]
